CREATE TABLE IF NOT EXISTS blog_posts (
  id SERIAL PRIMARY KEY,
  title VARCHAR(500) NOT NULL,
  slug VARCHAR(500) NOT NULL UNIQUE,
  content TEXT NOT NULL DEFAULT '',
  excerpt VARCHAR(1000),
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  source VARCHAR(50) NOT NULL DEFAULT 'manual',
  is_featured BOOLEAN NOT NULL DEFAULT false,
  view_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  published_at TIMESTAMPTZ,
  CONSTRAINT chk_status CHECK (status IN ('DRAFT', 'UNLISTED', 'PUBLISHED', 'ARCHIVED'))
);
