app.environment=dev

# Development environment admin credentials
admin.username=admin
admin.password=admin123

# Enable H2 console for dev (if needed)
spring.h2.console.enabled=true

# Flyway Configuration for Dev
spring.flyway.locations=classpath:db/migration
